import type { ProgressionSlot } from '@/store/progressionStore';
import { midiToNoteName } from '@/theory/notes';

function qualityLabel(quality: string): string {
  const labels: Record<string, string> = {
    major: 'Major',
    minor: 'Minor',
    dominant7: 'Dominant 7',
    major7: 'Major 7',
    minor7: 'Minor 7',
    diminished: 'Diminished',
    halfDim: 'Half Diminished',
    augmented: 'Augmented',
    sus2: 'Sus2',
    sus4: 'Sus4',
    dim7: 'Diminished 7',
    minMaj7: 'Minor Major 7',
  };
  return labels[quality] ?? quality;
}

export function generateChordChart(slots: ProgressionSlot[], bpm: number): string {
  const lines: string[] = [];

  lines.push('# Chord Progression Chart');
  lines.push(`**BPM:** ${bpm} | **Key:** C Ionian`);
  lines.push('');
  lines.push('## Progression');
  lines.push('');
  lines.push('| # | Chord | Roman Numeral | Quality | Notes |');
  lines.push('|---|-------|---------------|---------|-------|');

  for (let i = 0; i < slots.length; i++) {
    const slot = slots[i];
    const noteNames = slot.voicing
      .map((n) => midiToNoteName(n.midi))
      .join(', ');
    lines.push(
      `| ${i + 1} | ${slot.symbol} | ${slot.romanNumeral} | ${qualityLabel(slot.quality)} | ${noteNames} |`,
    );
  }

  lines.push('');
  lines.push('---');
  lines.push('Generated by Chord Mandala');

  return lines.join('\n');
}
