import { describe, it, expect } from 'vitest';
import { generateChordChart } from '../../src/export/chordChart';
import type { ProgressionSlot } from '../../src/store/progressionStore';

function makeSlot(
  symbol: string,
  romanNumeral: string,
  quality: string,
  midiNotes: number[],
): ProgressionSlot {
  return {
    id: 'test',
    rootIndex: 0,
    quality: quality as any,
    symbol,
    romanNumeral,
    voicing: midiNotes.map((midi) => ({ midi, delayMs: 0, velocity: 100 })),
  };
}

describe('generateChordChart', () => {
  it('returns a string with title', () => {
    const chart = generateChordChart([], 120);
    expect(chart).toContain('# Chord Progression Chart');
  });

  it('includes BPM', () => {
    const chart = generateChordChart([], 140);
    expect(chart).toContain('**BPM:** 140');
  });

  it('includes chord symbols', () => {
    const slots = [
      makeSlot('Cmaj7', 'I', 'major7', [60, 64, 67, 71]),
      makeSlot('Am7', 'vi', 'minor7', [57, 60, 64, 67]),
    ];
    const chart = generateChordChart(slots, 120);
    expect(chart).toContain('Cmaj7');
    expect(chart).toContain('Am7');
  });

  it('includes roman numerals', () => {
    const slots = [makeSlot('Cmaj7', 'I', 'major7', [60, 64, 67, 71])];
    const chart = generateChordChart(slots, 120);
    expect(chart).toContain('I');
  });

  it('includes note names from voicing', () => {
    const slots = [makeSlot('Cmaj7', 'I', 'major7', [60, 64, 67, 71])];
    const chart = generateChordChart(slots, 120);
    // C=60, E=64, G=67, B=71
    expect(chart).toContain('C');
    expect(chart).toContain('E');
    expect(chart).toContain('G');
    expect(chart).toContain('B');
  });

  it('has markdown table format', () => {
    const slots = [makeSlot('Cmaj7', 'I', 'major7', [60, 64, 67])];
    const chart = generateChordChart(slots, 120);
    expect(chart).toContain('| # | Chord | Roman Numeral | Quality | Notes |');
    expect(chart).toContain('|---|');
  });

  it('includes generated footer', () => {
    const chart = generateChordChart([], 120);
    expect(chart).toContain('Generated by Chord Mandala');
  });

  it('handles empty slots', () => {
    const chart = generateChordChart([], 120);
    expect(chart).toContain('# Chord Progression Chart');
    expect(chart).toContain('## Progression');
    // Should not have any data rows
    const tableRows = chart.split('\n').filter((l) => l.startsWith('| 1'));
    expect(tableRows.length).toBe(0);
  });
});
